# Generated by Django 3.2.13 on 2025-12-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_fa', models.CharField(blank=True, max_length=100, verbose_name='نام فارسی')),
                ('icon', models.CharField(default='bi-tag', max_length=50, verbose_name='آیکون')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('theme', models.CharField(choices=[('olive', 'زیتونی'), ('blu', 'آبی'), ('berry', 'تمشکی'), ('dark', 'تیره')], default='olive', max_length=20, verbose_name='تم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('type', models.CharField(choices=[('INCOME', 'درآمد'), ('EXPENSE', 'هزینه')], max_length=10, verbose_name='نوع')),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='دسته\u200cبندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('target_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ هدف')),
                ('current_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ فعلی')),
                ('deadline', models.CharField(max_length=10, verbose_name='مهلت')),
                ('icon', models.CharField(default='bi-trophy', max_length=50, verbose_name='آیکون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'هدف مالی',
                'verbose_name_plural': 'اهداف مالی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='سقف بودجه')),
                ('period', models.CharField(choices=[('MONTHLY', 'ماهانه'), ('WEEKLY', 'هفتگی')], default='MONTHLY', max_length=10, verbose_name='دوره')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='دسته\u200cبندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بودجه',
                'verbose_name_plural': 'بودجه\u200cها',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
